### ISSUE TITLE
Corriger faute nom dans premiere section

### ISSUE THREAD

**Issue by DarkPyroM** [ClubCedille/canoe-beton#30]
Il faut changer le nom "canoé béton" à "canoë béton"

**Comment by DarkPyroM** [comment]
faute corriger

**Comment by fxleblanc** [comment]
@DarkPyroM, pour éviter de fermer manuellement l'issue à chaque fois, tu peux tout simplement mettre "fix #30" où 30 va être ton numéro d'issue dans le message de ta pull request. Une fois que la pull request sera mergée, l'issue va se fermer automatiquement.
