### ISSUE TITLE
Migrer vers Wordpress ou garder le même fichier HTML mais l'avoir prégénéré? 

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/canoe-beton#90]
Durant la réunion avec Julie aujourd'hui, j'ai remarqué que le site était très difficilement déployable sur Windows. Une des raisons est un incompatibilité entre Node 12 et  Gulp 3. D'ailleurs, Gulp est déprécié depuis au moins 2017.

Il y a deux issues au problèmes, soit:
* Il faudra migrer vers Wordpress. Le site devra être recréé au complet. 
* Prégénérer le site qui était généré par Gulp pour qu'on puisse que modifier le HTML pour faire les changements facilement. 

_Edit: s/Gulf/Gulp/g_

**Comment by notarock** [comment]
Pas d'activité en 2 semaines, je ferme.

**Comment by AXDOOMER** [comment]
@jalilbengoufa  Des updates là-dessus?

**Comment by jalilbengoufa** [comment]
ils vont garder le même site et à moins quelqu'un du club veut faire un nouveau site.

**Comment by AXDOOMER** [comment]
Comment ils vont faire pour le modifier sans membre qui est assez _tech savvy_ pour le faire?

**Comment by jalilbengoufa** [comment]
Ils l'ont déjà fait en suivant le readme, sinon ils peuvent demander un quelqu'un qui connaît un peut git et html ça ne prend pas un génie pour faire ça. Sinon ça revient au message qui j'ai écrit plus haut.

**Comment by AXDOOMER** [comment]
Ça fait longtemps et ils ont pu les membres qui se chargeaient de ça. On leur dira de recruter quelqu'un en LOG s'ils ne veulent plus migrer à Wordpress.
